# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0014_auto_20170831_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', help_text='Ingresa el tipo de telefono', max_length=24)),
                ('numero', models.CharField(default='', help_text='Ingresa un numero no mayor a 16 digitos', max_length=12)),
                ('cargo', models.CharField(blank=True, default='', max_length=28, null=True)),
                ('fecha_de_registro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contacto')),
                ('telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Empresa')),
                ('telefono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Telefono')),
            ],
        ),
    ]
