# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telefonocontacto',
            options={'verbose_name': 'Teléfono del Contacto', 'verbose_name_plural': 'Teléfonos del Contácto'},
        ),
        migrations.AlterModelOptions(
            name='telefonoempresa',
            options={'verbose_name': 'Teléfono de la Empresa', 'verbose_name_plural': 'Teléfonos de la Empresa'},
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='telefono',
            name='fecha_de_registro',
        ),
    ]
